nodes:
  mongodb:
    type: mongodb
    uri: mongodb://mongo1/rental_apartments
    namespace: rental_apartments.apartments
    debug: true
  es:
    type: elasticsearch
    uri: http://elasticsearch:9200/
  logtransformer:
    filename: test/transformers/passthrough_and_log.js
    type: transformer
